import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
  const { data: session } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (session?.user.role === "admin") {
      void router.replace("/dashboard")
    } else {
      void router.replace("/login")
    }
  }, []);


  return (
    <>
      <Head>
        <title>Shine | Youth Unlimited</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
